name: Test & deploy

on:
    push:
        branches: [master]
        tags:
            - "**"
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: "11"
                  distribution: "adopt"

            - name: Cache
              uses: actions/cache@v2.1.6
              with:
                  path: /home/runner/.m2/repository
                  key: ${{ runner.os }}-${{ hashFiles('pom.xml') }}

            - name: Build with Maven
              run: mvn -B test --file pom.xml

    github-release:
        needs: test
        if: startsWith(github.ref, 'refs/tags/') # run this step only when tagged
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: "11"
                  distribution: "adopt"

            - name: Cache
              uses: actions/cache@v2.1.6
              with:
                  path: /home/runner/.m2/repository
                  key: ${{ runner.os }}-${{ hashFiles('pom.xml') }}

            - name: Build with Maven
              run: mvn -B package --file pom.xml -DskipTests=true

            - name: Create release archive
              run: |
                  mkdir packager-tmp && cp -r resources/* ./packager-tmp && cp target/*.jar ./packager-tmp
                  cd ./packager-tmp && tar -czvf joal.tar.gz * && mv ./joal.tar.gz ../ && cd ..

            - name: Create Github release
              uses: ncipollo/release-action@v1.8.6
              with:
                  allowUpdates: true
                  artifactErrorsFailBuild: true
                  artifacts: "joal.tar.gz"
                  draft: true
                  token: ${{ secrets.GITHUB_TOKEN }}

    push-to-docker-hub:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              if: github.event_name != 'pull_request'
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            - name: Update Docker Hub description
              uses: peter-evans/dockerhub-description@v4
              if: github.event_name != 'pull_request'
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

    push-to-github-packages:
        name: Push Docker image to GitHub Packages
        runs-on: ubuntu-latest

        env:
            REGISTRY: ghcr.io

        permissions:
            contents: read
            packages: write

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Log in to GitHub Packages
              uses: docker/login-action@v3
              if: github.event_name != 'pull_request'
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
